services:
  - type: worker
    name: homework-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: BOT_TOKEN
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: CALENDAR_ID
        value: primary
      - key: TIMEZONE
        value: Europe/Moscow
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GOOGLE_TOKEN_JSON
        sync: false
